FROM nginx:stable-alpine

# Ensure to have the same userid and username as in the php-fpm container to avoid permission conflicts
RUN set -x \
 && addgroup -g 82 -S www-data \
 && adduser -u 82 -D -S -G www-data www-data

###################
# Cleanup defaults
###################
RUN rm /etc/nginx/conf.d/default.conf

###################
# Nginx settings
###################
COPY ./docker/nginx/nginx_conf/ /etc/nginx/
COPY ./docker/nginx/nginx_sites/ /etc/nginx/conf.d/

EXPOSE 80
EXPOSE 443
